// Common events
export const COMMON_RESET_STATE = 'COMMON_RESET_STATE'
export const COMMON_SET_SEMAPHORE = 'COMMON_SET_SEMAPHORE'
export const COMMON_CLEAR_SEMAPHORE = 'COMMON_CLEAR_SEMAPHORE'
export const COMMON_INIT_COLLECTION = 'COMMON_INIT_COLLECTION'

export const COMMON_PUSH_INTO_QUEUE = 'COMMON_PUSH_INTO_QUEUE'
export const COMMON_REPLACE_IN_QUEUE = 'COMMON_REPLACE_IN_QUEUE'
export const COMMON_POP_FROM_QUEUE = 'COMMON_POP_FROM_QUEUE'

// Application
export const APP_STORE_CONNECTION_STATUS = 'APP_STORE_CONNECTION_STATUS'
