// Common events
export const IO_SERVER_RESET_STATE = 'IO_SERVER_RESET_STATE'
export const IO_SERVER_SET_SEMAPHORE = 'IO_SERVER_SET_SEMAPHORE'
export const IO_SERVER_CLEAR_SEMAPHORE = 'IO_SERVER_CLEAR_SEMAPHORE'
export const IO_SERVER_INIT_COLLECTION = 'IO_SERVER_INIT_COLLECTION'

export const IO_SERVER_PUSH_INTO_QUEUE = 'IO_SERVER_PUSH_INTO_QUEUE'
export const IO_SERVER_REPLACE_IN_QUEUE = 'IO_SERVER_REPLACE_IN_QUEUE'
export const IO_SERVER_POP_FROM_QUEUE = 'IO_SERVER_POP_FROM_QUEUE'
