export const ACCOUNTS_NODE_SESSION = 'accounts-node/session'
export const ACCOUNTS_NODE_ACCOUNT = 'accounts-node/account'
export const ACCOUNTS_NODE_EMAIL = 'accounts-node/email'
export const ACCOUNTS_NODE_SECURITY_QUESTION = 'accounts-node/security-question'
export const ACCOUNTS_NODE_SYSTEM_IDENTITY = 'accounts-node/system-identity'
