// Common events
export const STORE_BASE_RESET_STATE = 'STORE_BASE_RESET_STATE'
export const STORE_BASE_SET_SEMAPHORE = 'STORE_BASE_SET_SEMAPHORE'
export const STORE_BASE_CLEAR_SEMAPHORE = 'STORE_BASE_CLEAR_SEMAPHORE'
export const STORE_BASE_INIT_COLLECTION = 'STORE_BASE_INIT_COLLECTION'

export const STORE_BASE_PUSH_INTO_QUEUE = 'STORE_BASE_PUSH_INTO_QUEUE'
export const STORE_BASE_REPLACE_IN_QUEUE = 'STORE_BASE_REPLACE_IN_QUEUE'
export const STORE_BASE_POP_FROM_QUEUE = 'STORE_BASE_POP_FROM_QUEUE'
